[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

[[redirects]]
  from = "/*"
  to = "/?uni_id=16763"
  status = 200
  force = false
  query = {path = ":path"}
  conditions = {Country = ["mc"]}

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable
    '''