// Generated by https://quicktype.io

export interface University {
  "uni-id": number;
  "uni-name": string;
  "en-name": null;
  abr: string;
  country_id: number;
  city: string;
  address: string;
  description: string;
  "uni-tel": string;
  "uni-pic": string;
  "uni-logo": string;
  "uni-lon": null;
  url: string;
  country: Country;
}

export interface Country {
  id: number;
  iso2: string;
  iso3: string;
  name: string;
  currency: string;
  currency_iso: string;
}
